version: '3.8'

services:
  db:
    image: postgres:13
    volumes:
      - db-data-cursed:/var/lib/postgresql/data
      - ./init.psql:/docker-entrypoint-initdb.d/init.psql
    environment:
      POSTGRES_DB: raptor
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: raptor_password
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data-cursed:
